### ISSUE TITLE
Locked things bug

### ISSUE THREAD

**Issue by 00c** [HybridDog/replacer#4] opened 2018-02-07 14:21 UTC
Could you please disable node replacer on locked things as locked chests, itemframes and so on, also on doors there are more nodes like furniture and so on.
 Locked things placed with replacer have no owner.

**Comment by HybridDog** [comment] 2018-02-07 20:11
Currently set_node is used for placing nodes (https://github.com/HybridDog/replacer/blob/master/init.lua#L363).
I think using a place function would fix this bug.

**Comment by HybridDog** [comment] 2018-02-08 16:47
It should be fixed now: https://github.com/HybridDog/replacer/commit/284d73ff3a434aaf038348b5e30e57ea65797cc9

**Comment by 00c** [comment] 2018-02-08 17:36
I just try it out, Server crashes when i try use node replacer.

> `2018-02-08 18:32:34: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'hbhunger' in callback item_OnUse(): /mt/bin/../builtin/game/
> item.lua:218: attempt to index local 'placer' (a nil value)
> 2018-02-08 18:32:34: ERROR[Main]: stack traceback:
> 2018-02-08 18:32:34: ERROR[Main]:       /mt/bin/../builtin/game/item.lua:218: in function </mt/bin/../builtin/game/item.lua:208>
> 2018-02-08 18:32:34: ERROR[Main]:       (tail call): ?
> 2018-02-08 18:32:34: ERROR[Main]:       (tail call): ?
> 2018-02-08 18:32:34: ERROR[Main]:       .../bin/../games/Liberty Land/mods/replacer/init.lua:410: in function 'replace_single_node'
> 2018-02-08 18:32:34: ERROR[Main]:       .../bin/../games/Liberty Land/mods/replacer/init.lua:495: in function <.../bin/../games/Liberty Land/mods/replacer/init.lua:443>
> 2018-02-08 18:32:34: ERROR[Main]:       (tail call): ?`

**Comment by HybridDog** [comment] 2018-02-08 18:25
Sorry, it should be fixed now.

**Comment by 00c** [comment] 2018-02-13 18:18
Fixed, But there is a new bug. When you replace an item its placed wrong way. Node replacer place correct Node but wrong way/rotation Looks similar as if you place it with hand. When you replace it again it rotates correct way.

**Comment by HybridDog** [comment] 2018-02-13 20:30
I couldn't reproduce this (tested by (re)placing chest and stair with replacer).
Can you tell me how to concretely reproduce it?

**Comment by 00c** [comment] 2018-02-13 21:01
does not happen always.  Looks as it happen when you try replace same slope from moreblocks mod.
![exapmle](https://user-images.githubusercontent.com/15174768/36173390-247f4f9a-1109-11e8-8c66-3c9780847509.png)
I copy left snow brick stair and replace one brick stair two left from three on right side. As you can see rotation is wrong.
Node is replaced with wrong rotation. As you can see error message appear too while node is replaced.

**Comment by HybridDog** [comment] 2018-02-14 08:49
It tells that placing the stair didn't work.
https://github.com/HybridDog/replacer/blob/master/init.lua#L408
After the current node is dug, the new node is placed the way a player would place it (for adding chest inventory etc.).
For usual nodes, that function is used which returns a success boolean: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3172 
If placing didn't succeed (i.e. success is false or nil), the replacer function aborts, else it takes the item from the inventory and fixes rotation. 
I guess this could be fixed by only aborting if success is false (nil would mean placing may have succeeded).

**Comment by HybridDog** [comment] 2018-02-15 13:20
I changed it, pls test.

**Comment by 00c** [comment] 2018-03-05 13:46
Sorry for late reply. 
It works fine now. Thanks for quick fix!

**Closed as completed** 2018-03-05 14:30 UTC
